# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Crypto Boost' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crypto Boost

pod 'SnapKit', '~> 5.7.0'
pod 'Kingfisher', '~> 7.0'
end
